[package]
name = "sbb"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
rand = "0.9.1"
hex = "0.4"
sha2 = "0.10"
common = { path = "../common" }
tempfile = "3.20.0"

[build-dependencies]
cc = "1.0"
